services:
  api:
    build:
      context: ./Sql.Baseline.Api  # or your actual path
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Server=sql;Database=BaselineDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      Redis__ConnectionString: redis:6379,abortConnect=false
      Jwt__Authority: https://baselinedoz.example.com/
      Jwt__Audience: sql-baseline-api
      # optional: override Serilog via env
      # Serilog__WriteTo__1__Name: Seq
      # Serilog__WriteTo__1__Args__serverUrl: http://seq
    depends_on:
      sql:
        condition: service_healthy
      redis:
        condition: service_started
      seq:
        condition: service_started
    ports:
      - "8080:8080"

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports: [ "1433:1433" ]
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd","-S","localhost","-U","sa","-P","Your_password123","-C","-Q","SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]

  seq:
    image: datalust/seq:2024
    environment: [ "ACCEPT_EULA=Y" ]
    ports: [ "5341:80" ]  # host 5341 -> container 80
